# -*- coding: utf-8 -*-
"""AddNumbers_Tyler_Fuller.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bgQMWpki_Z4ak_LbUUlR1LTo9B2acpyZ
"""

# User input two numbers, either decimal or integer
num1 = float(input("Enter first number "))
num2 = float(input("Enter second number "))

# Compute sum
sum = num1+num2

# Output sum to the console
print("Sum is", sum)